/**
 * This example script expects a JSON blob generated by react-docgen as input,
 * e.g. react-docgen components/* | buildDocs.sh
 */
const through = require('through2');
const File = require('vinyl');
const docgen = require('react-docgen');

const paths = require('./paths.json');

/**
 * The quick-and-dirty react-docgen plugin
 * @return {Stream} The stream
 */
const plugin = function plugin(options = {}) {
    // implement the default options
    //
    const opts = Object.assign({
        name: 'react-docgen.json',
    }, options);

    // declare a variable to hold the list of files
    //
    const fileList = [];

    return through.obj(

        function write(file, encoding, callback) {
            // is the file null? if so, just carry on
            //
            if (file.isNull()) {
                return callback(null, file);
            }

            // add the file to the list of files
            //
            fileList.push(file);

            // carry on...
            //
            callback();
        },

        function end(callback) {
            // declare a variable to hold the results
            //
            const result = {};

            // iterate over the list of files
            //
            fileList.forEach((file) => {
                // get the file contents
                //
                const content = file.contents.toString();

                // declare a variable to hold the results
                //
                let doc = null;

                // attempt to parse the content
                //
                try {
                    doc = docgen.parse(content);
                } catch (err) {
                    // log the error?
                }

                // did we get some parsed content? if so, add it to the results
                if (doc) {
                    result[file.relative] = doc;
                }
            });

            // push the new file containing the JSON-encoded results
            //
            this.push(new File({
                contents: new Buffer(JSON.stringify(result, null, '  ')),
                base:     '/tmp',
                path:     '/tmp/test2.json',
            }));

            // carry on...
            //
            callback();
        }

    );
};


module.exports = (gulp) =>
    gulp.src(paths.source)
        .pipe(plugin())
        .pipe(gulp.dest('./'));
